### ISSUE TITLE
Get IndexError when pressing CTRL-C

### ISSUE THREAD

**Issue by ThatXliner** [HallerPatrick/frosch#35]
When I interrupt the keyboard (<kbd>ctrl</kbd> + <kbd>c</kbd>), I get
```python
Error in sys.excepthook:
Traceback (most recent call last):
  File "REDACTED/.venv/lib/python3.6/site-packages/frosch/frosch.py", line 56, in pytrace_excepthook
    parsed_exception = ParsedException(traceback_, error_type, error_message)
  File "REDACTED/.venv/lib/python3.6/site-packages/frosch/parser.py", line 68, in __init__
    self.last_stack = traceback.extract_tb(traceback_)[-1]
IndexError: list index out of range

Original exception was:
KeyboardInterrupt
```

**Comment by HallerPatrick** [comment]
I cannot really replicate this error. How did you do it? I still included some exception handling if no stack traces can be extract from the traceback. So no errors should be thrown from `frosch`
