### ISSUE TITLE
Doesn't work with multiline statements

### ISSUE THREAD

**Issue by alexmojaki** [HallerPatrick/frosch#9]
Example script:

```python
import frosch

frosch.hook()

x = (
  1 +
  "2"
)
```

Output:

```pytb
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/frosch/frosch.py", line 47, in pytrace_excepthook
    names = parse_error_line(last_stack.line)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/frosch/frosch.py", line 71, in parse_error_line
    tree = ast.parse(line)
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    1 +
      ^
SyntaxError: invalid syntax

Original exception was:
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    1 +
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

In general you may be interested in using https://github.com/alexmojaki/stack_data as part of this library

**Comment by HallerPatrick** [comment]
Thank you. stack_data looks interesting and could help here out
